/**
 * Design exploration themes for /theme only.
 * Does not mutate the live portfolio brand tokens.
 */

export type SemanticThemeTokens = {
  background: string;
  surface: string;
  elevated: string;
  border: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  primary: string;
  secondary: string;
  accent: string;
  buttonPrimary: string;
  buttonPrimaryText: string;
  buttonSecondary: string;
  buttonSecondaryText: string;
  buttonHover: string;
  buttonActive: string;
  link: string;
  badge: string;
  badgeText: string;
  tag: string;
  tagText: string;
  success: string;
  warning: string;
  error: string;
  hover: string;
};

export type ExplorationTheme = {
  id: string;
  name: string;
  description: string;
  personality: string;
  dark: SemanticThemeTokens;
  light: SemanticThemeTokens;
};

/** CSS custom properties scoped to exploration previews */
export function tokensToCssVars(
  tokens: SemanticThemeTokens,
): Record<string, string> {
  return {
    "--ex-background": tokens.background,
    "--ex-surface": tokens.surface,
    "--ex-elevated": tokens.elevated,
    "--ex-border": tokens.border,
    "--ex-text-primary": tokens.textPrimary,
    "--ex-text-secondary": tokens.textSecondary,
    "--ex-text-muted": tokens.textMuted,
    "--ex-primary": tokens.primary,
    "--ex-secondary": tokens.secondary,
    "--ex-accent": tokens.accent,
    "--ex-btn-primary": tokens.buttonPrimary,
    "--ex-btn-primary-text": tokens.buttonPrimaryText,
    "--ex-btn-secondary": tokens.buttonSecondary,
    "--ex-btn-secondary-text": tokens.buttonSecondaryText,
    "--ex-btn-hover": tokens.buttonHover,
    "--ex-btn-active": tokens.buttonActive,
    "--ex-link": tokens.link,
    "--ex-badge": tokens.badge,
    "--ex-badge-text": tokens.badgeText,
    "--ex-tag": tokens.tag,
    "--ex-tag-text": tokens.tagText,
    "--ex-success": tokens.success,
    "--ex-warning": tokens.warning,
    "--ex-error": tokens.error,
    "--ex-hover": tokens.hover,
  };
}

export const explorationThemes: ExplorationTheme[] = [
  {
    id: "crimson-authority",
    name: "Crimson Authority",
    description:
      "A confident deep-red product aesthetic—decisive, editorial, and built for trust.",
    personality: "Bold · Editorial · Decisive",
    dark: {
      background: "#0C0A0A",
      surface: "#161212",
      elevated: "#1F1919",
      border: "#2E2424",
      textPrimary: "#FAF7F6",
      textSecondary: "#D4C8C5",
      textMuted: "#9A8B87",
      primary: "#B91C1C",
      secondary: "#7F1D1D",
      accent: "#F87171",
      buttonPrimary: "#B91C1C",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#FAF7F6",
      buttonHover: "#DC2626",
      buttonActive: "#991B1B",
      link: "#F87171",
      badge: "rgba(185, 28, 28, 0.16)",
      badgeText: "#FCA5A5",
      tag: "#1F1919",
      tagText: "#D4C8C5",
      success: "#059669",
      warning: "#D97706",
      error: "#EF4444",
      hover: "#241C1C",
    },
    light: {
      background: "#FFFBFA",
      surface: "#FFFFFF",
      elevated: "#F7F1F0",
      border: "#E8DDDA",
      textPrimary: "#1C1412",
      textSecondary: "#4A3B37",
      textMuted: "#7A6863",
      primary: "#B91C1C",
      secondary: "#7F1D1D",
      accent: "#DC2626",
      buttonPrimary: "#B91C1C",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#1C1412",
      buttonHover: "#991B1B",
      buttonActive: "#7F1D1D",
      link: "#B91C1C",
      badge: "rgba(185, 28, 28, 0.1)",
      badgeText: "#991B1B",
      tag: "#F7F1F0",
      tagText: "#4A3B37",
      success: "#047857",
      warning: "#B45309",
      error: "#DC2626",
      hover: "#F3EBE9",
    },
  },
  {
    id: "emerald-executive",
    name: "Emerald Executive",
    description:
      "Elegant green with a calm SaaS finish—precise, trustworthy, quietly premium.",
    personality: "Calm · Precise · Institutional",
    dark: {
      background: "#070C0A",
      surface: "#0F1613",
      elevated: "#16201B",
      border: "#24332C",
      textPrimary: "#F4FBF7",
      textSecondary: "#C5D5CC",
      textMuted: "#8AA397",
      primary: "#059669",
      secondary: "#064E3B",
      accent: "#34D399",
      buttonPrimary: "#059669",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#F4FBF7",
      buttonHover: "#10B981",
      buttonActive: "#047857",
      link: "#34D399",
      badge: "rgba(5, 150, 105, 0.16)",
      badgeText: "#6EE7B7",
      tag: "#16201B",
      tagText: "#C5D5CC",
      success: "#10B981",
      warning: "#D97706",
      error: "#F87171",
      hover: "#1A2821",
    },
    light: {
      background: "#F7FBF9",
      surface: "#FFFFFF",
      elevated: "#EEF6F1",
      border: "#D5E5DB",
      textPrimary: "#0B1A14",
      textSecondary: "#2F4A3D",
      textMuted: "#5C7A6B",
      primary: "#047857",
      secondary: "#065F46",
      accent: "#059669",
      buttonPrimary: "#047857",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#0B1A14",
      buttonHover: "#065F46",
      buttonActive: "#064E3B",
      link: "#047857",
      badge: "rgba(4, 120, 87, 0.1)",
      badgeText: "#065F46",
      tag: "#EEF6F1",
      tagText: "#2F4A3D",
      success: "#059669",
      warning: "#B45309",
      error: "#DC2626",
      hover: "#E5F0EA",
    },
  },
  {
    id: "graphite-gold",
    name: "Graphite & Gold",
    description:
      "Luxury minimal—graphite structure with restrained metallic highlights.",
    personality: "Luxury · Minimal · Refined",
    dark: {
      background: "#0A0A0B",
      surface: "#121214",
      elevated: "#1A1A1E",
      border: "#2A2A30",
      textPrimary: "#F7F6F2",
      textSecondary: "#CFCBBF",
      textMuted: "#9A968A",
      primary: "#C9A227",
      secondary: "#8A7020",
      accent: "#E8C547",
      buttonPrimary: "#C9A227",
      buttonPrimaryText: "#14110A",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#F7F6F2",
      buttonHover: "#D4AF37",
      buttonActive: "#A8861F",
      link: "#E8C547",
      badge: "rgba(201, 162, 39, 0.14)",
      badgeText: "#E8C547",
      tag: "#1A1A1E",
      tagText: "#CFCBBF",
      success: "#22C55E",
      warning: "#EAB308",
      error: "#F87171",
      hover: "#222228",
    },
    light: {
      background: "#FAFAF8",
      surface: "#FFFFFF",
      elevated: "#F3F2EC",
      border: "#E4E1D6",
      textPrimary: "#14140F",
      textSecondary: "#3F3D34",
      textMuted: "#6F6B5E",
      primary: "#A8861F",
      secondary: "#8A7020",
      accent: "#C9A227",
      buttonPrimary: "#A8861F",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#14140F",
      buttonHover: "#8A7020",
      buttonActive: "#6F5A18",
      link: "#8A7020",
      badge: "rgba(168, 134, 31, 0.12)",
      badgeText: "#6F5A18",
      tag: "#F3F2EC",
      tagText: "#3F3D34",
      success: "#15803D",
      warning: "#A16207",
      error: "#B91C1C",
      hover: "#ECEAE2",
    },
  },
  {
    id: "burnt-orange-studio",
    name: "Burnt Orange Studio",
    description:
      "Creative warmth with professional restraint—studio energy without noise.",
    personality: "Warm · Creative · Grounded",
    dark: {
      background: "#0D0A08",
      surface: "#17120E",
      elevated: "#211A14",
      border: "#34291F",
      textPrimary: "#FBF7F2",
      textSecondary: "#D9CDBF",
      textMuted: "#A39484",
      primary: "#C2410C",
      secondary: "#7C2D12",
      accent: "#FB923C",
      buttonPrimary: "#C2410C",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#FBF7F2",
      buttonHover: "#EA580C",
      buttonActive: "#9A3412",
      link: "#FB923C",
      badge: "rgba(194, 65, 12, 0.16)",
      badgeText: "#FDBA74",
      tag: "#211A14",
      tagText: "#D9CDBF",
      success: "#16A34A",
      warning: "#D97706",
      error: "#EF4444",
      hover: "#2A2119",
    },
    light: {
      background: "#FFFBF7",
      surface: "#FFFFFF",
      elevated: "#F7EFE7",
      border: "#E8D9CB",
      textPrimary: "#1A130E",
      textSecondary: "#4A382C",
      textMuted: "#7A6454",
      primary: "#C2410C",
      secondary: "#9A3412",
      accent: "#EA580C",
      buttonPrimary: "#C2410C",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#1A130E",
      buttonHover: "#9A3412",
      buttonActive: "#7C2D12",
      link: "#C2410C",
      badge: "rgba(194, 65, 12, 0.1)",
      badgeText: "#9A3412",
      tag: "#F7EFE7",
      tagText: "#4A382C",
      success: "#15803D",
      warning: "#B45309",
      error: "#DC2626",
      hover: "#F0E6DB",
    },
  },
  {
    id: "obsidian-teal",
    name: "Obsidian Teal",
    description:
      "Dark engineering clarity with a cool teal signal—modern tools, not neon nights.",
    personality: "Technical · Cool · Focused",
    dark: {
      background: "#070B0C",
      surface: "#0E1416",
      elevated: "#151D20",
      border: "#243035",
      textPrimary: "#F2F7F8",
      textSecondary: "#C2D0D4",
      textMuted: "#87999F",
      primary: "#0D9488",
      secondary: "#115E59",
      accent: "#2DD4BF",
      buttonPrimary: "#0D9488",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#F2F7F8",
      buttonHover: "#14B8A6",
      buttonActive: "#0F766E",
      link: "#2DD4BF",
      badge: "rgba(13, 148, 136, 0.16)",
      badgeText: "#5EEAD4",
      tag: "#151D20",
      tagText: "#C2D0D4",
      success: "#10B981",
      warning: "#F59E0B",
      error: "#F87171",
      hover: "#1B262A",
    },
    light: {
      background: "#F0F6F8",
      surface: "#FFFFFF",
      elevated: "#E8F0F2",
      border: "#A8C0C6",
      textPrimary: "#0C1214",
      textSecondary: "#1A2A2E",
      textMuted: "#314347",
      primary: "#0D9488",
      secondary: "#0F766E",
      accent: "#0D9488",
      buttonPrimary: "#0D9488",
      buttonPrimaryText: "#FFFFFF",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#0C1214",
      buttonHover: "#0F8A7E",
      buttonActive: "#0A5C56",
      link: "#0D9488",
      badge: "rgba(13, 148, 136, 0.16)",
      badgeText: "#0D9488",
      tag: "#E8F0F2",
      tagText: "#1A2A2E",
      success: "#047857",
      warning: "#B45309",
      error: "#DC2626",
      hover: "#D5E6E9",
    },
  },
  {
    id: "monochrome-plus",
    name: "Monochrome Plus",
    description:
      "Near-neutral structure with one sharp interaction accent—maximum craft, minimal color.",
    personality: "Neutral · Sharp · Product-native",
    dark: {
      background: "#09090B",
      surface: "#111113",
      elevated: "#18181B",
      border: "#27272A",
      textPrimary: "#FAFAFA",
      textSecondary: "#D4D4D8",
      textMuted: "#A1A1AA",
      primary: "#FAFAFA",
      secondary: "#A1A1AA",
      accent: "#38BDF8",
      buttonPrimary: "#FAFAFA",
      buttonPrimaryText: "#09090B",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#FAFAFA",
      buttonHover: "#E4E4E7",
      buttonActive: "#D4D4D8",
      link: "#38BDF8",
      badge: "rgba(56, 189, 248, 0.14)",
      badgeText: "#7DD3FC",
      tag: "#18181B",
      tagText: "#D4D4D8",
      success: "#22C55E",
      warning: "#EAB308",
      error: "#F87171",
      hover: "#1F1F23",
    },
    light: {
      background: "#FAFAFA",
      surface: "#FFFFFF",
      elevated: "#F4F4F5",
      border: "#E4E4E7",
      textPrimary: "#09090B",
      textSecondary: "#3F3F46",
      textMuted: "#71717A",
      primary: "#18181B",
      secondary: "#52525B",
      accent: "#0284C7",
      buttonPrimary: "#18181B",
      buttonPrimaryText: "#FAFAFA",
      buttonSecondary: "transparent",
      buttonSecondaryText: "#09090B",
      buttonHover: "#27272A",
      buttonActive: "#09090B",
      link: "#0284C7",
      badge: "rgba(2, 132, 199, 0.1)",
      badgeText: "#0369A1",
      tag: "#F4F4F5",
      tagText: "#3F3F46",
      success: "#15803D",
      warning: "#A16207",
      error: "#B91C1C",
      hover: "#ECECEE",
    },
  },
];

export const RECOMMENDED_THEME_ID = "obsidian-teal";

export function getExplorationTheme(id: string): ExplorationTheme | undefined {
  return explorationThemes.find((t) => t.id === id);
}
